local DIRECTION_ANIMATION = {}

DIRECTION_ANIMATION.WALK_UP     = 2
DIRECTION_ANIMATION.WALK_RIGHT  = 4
DIRECTION_ANIMATION.WALK_DOWN   = 1
DIRECTION_ANIMATION.WALK_LEFT   = 3

return DIRECTION_ANIMATION
